# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataTerminio', models.DateField(verbose_name='Data de Terminio')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
            ],
        ),
        migrations.CreateModel(
            name='MembroParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorResponsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matricula')),
                ('cpfProfessor', models.CharField(max_length=20, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataTerminio', models.DateField(verbose_name='Data de Terminio')),
                ('justificativa', models.CharField(max_length=200, verbose_name='Justificativa')),
                ('metodologia', models.CharField(max_length=200, verbose_name='Metodologia')),
                ('resultado', models.CharField(max_length=200, verbose_name='Resultado esperado')),
                ('membro', models.ManyToManyField(to='appprojetos.MembroParticipante')),
                ('professorResponsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.ProfessorResponsavel', verbose_name='Professor Responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagioDesenvolvimento', models.CharField(max_length=200, verbose_name='Estagio desenvolvimento')),
                ('dataRegistro', models.DateField(verbose_name='Data de Registro')),
                ('DescricaoDesenvolvimento', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='projetoPesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.ProjetoPesquisa', verbose_name='Projeto Pesquisa'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.RegistroAcompanhamento', verbose_name='Registro Acompanhamento'),
        ),
    ]
