# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprojetos', '0002_remove_professorresponsavel_projetosubmetido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='nome',
        ),
    ]
