# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojetos', '0003_remove_atividade_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroparticipante',
            name='projetoPesquisa',
        ),
        migrations.AddField(
            model_name='projetopesquisa',
            name='membro',
            field=models.ManyToManyField(to='appprojetos.MembroParticipante'),
        ),
    ]
