# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprojetos', '0004_auto_20160617_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResgistroAcompanhamento',
            new_name='RegistroAcompanhamento',
        ),
    ]
