# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojetos', '0005_auto_20160617_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorresponsavel',
            name='matricula',
            field=models.CharField(max_length=10, verbose_name='Matricula'),
        ),
    ]
